name: Rom Poster Bot

on:
  push:
    paths-ignore:
      - '.github/scripts/file_ids.txt'
      - 'README.md'
  workflow_dispatch:

env:
  GitHubMail: "projectelixirbot@gmail.com"
  GitHubName: "TheElixirRobot"
  GitHubToken: ${{ secrets.GH_TOKEN }}
  BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
  CHAT_ID: ${{ secrets.CHAT_ID }}
  PRIV_CHAT_ID: ${{ secrets.PRIV_CHAT_ID }}
  ELIXIR_VERSION_CHECK: ${{ secrets.ELIXIR_VERSION_CHECK }}
  STICKER_ID: ${{ secrets.STICKER_ID }}
  BANNER_URL_T: ${{ secrets.BANNER_URL_T }}
  NOTES: ${{ secrets.NOTES }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: sudo pip install pyTelegramBotAPI

      - name: Set Git Configs & Secrets
        run: |
          git config --global user.email ${GitHubMail}
          git config --global user.name ${GitHubName}
          git config --global color.ui true
          git config --global credential.helper store
          echo "https://${GitHubName}:${GitHubToken}@github.com" > ~/.git-credentials
      - name: Run RomPosterBot
        run: sudo -E python3 .github/scripts/post.py

      - name: Commit and Push Changes
        run: | 
          git fetch && git pull
          COMMIT_MESSAGE=$(cat commit_mesg.txt)
          rm commit_mesg.txt
          git add . && git commit -sm "$COMMIT_MESSAGE"
          git push origin A13
          
- name: Gatsby CLI wrapper on node12
  # You may pin to the exact commit or the version.
  # uses: theWhiteWulfy/gatsby-cli-github-action@ae7b3bcc05f4e8ad3f53105cb7b19f9859619a55
  uses: theWhiteWulfy/gatsby-cli-github-action@2.0.c
  with:
    # Arguments to pass to Gatsby CLI
    gatsby-arg: # default is build
